name: STAGING deployment

on:
  push:
    branches:
      - v2-staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14.5.0'

    - name: Install dependencies
      run: |
        npm install -g yarn
        npm install
        yarn install

    # NOTE: Do NOT use trailing slashes in the URLs.
    # ATTENTION: `BASE_URL` must have the HTTP(S) protocol, but other URLs must not.
    - name: Build yarn
      env:
        CI: false
        BUILD_ENV: staging
        BASE_URL: https://coronavirus-staging.data.gov.uk
        MAIN_CDN: c19pubstaging.azureedge.net
        DOWNLOADS_CDN: c19downloadsstaging.azureedge.net
        API_ENDPOINT: api.coronavirus-staging.data.gov.uk
        NODE_ENV: production

      run: |
        yarn run build

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'Covid19StaticSTAGING'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICESTAGING }}
        package: ./build
