# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: PRODUCTION deployment

on:
  release:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v2.1.1
      with:
        node-version: '14.5.0'
    
    - name: Install dependencies
      run: |
        npm install -g yarn
        npm install
        yarn install

    # NOTE: Do NOT use trailing slashes in the URLs.
    # ATTENTION: `BASE_URL` must have the HTTP(S) protocol, but other URLs must not.
    - name: Build yarn
      env:
        CI: false
        BUILD_ENV: production
        BASE_URL: https://coronavirus.data.gov.uk
        MAIN_CDN: c19pub.azureedge.net
        DOWNLOADS_CDN: c19downloads.azureedge.net
        API_ENDPOINT: api.coronavirus.data.gov.uk
        NODE_ENV: production

      run: |
        yarn run build


    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2.1.3
      with:
        app-name: 'covid19static'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppServiceProd }}
        package: ./build
